# Analyse de données numériques - Exercices

Pour tous les exercices, le niveau de difficulté est indiqué par le code suivant :
* \* niveau facile
* \** niveau intermédiaire
* \*** niveau difficile

* **@** indique les exercices pour lesquels vous aurez besoin de chercher sur internet pour trouver des pistes de solution ou des exemples de code.

_Note : Pour faciliter la navigation dans les exercices, n'hésitez pas à activer l'extension "Table of Contents", après avoir installé les extensions de notebook `jupyter_contrib_nbextensions` (voir PDF sur la plateforme)._

## Numpy

D'abord, importer Numpy !

In [2]:
import numpy as np

### Exercice 1 – Créer une matrice numpy (*)
Créer une matrice 4x4 avec des valeurs allant de 2 à 17.

In [51]:
matrice = np.arange(16).reshape(4,4) + 2
matrice 

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

### Exercice 2 - Sélectionner un élément dans un array (*, @)

Trouver le 23ème élément de l'array numpy ci-dessous. 

_Indice : L'une des solutions utilise une méthode numpy specifique que vous pourrez trouver sur internet. Une autre solution utilise `//` et `%`._

In [24]:
array = np.array([[29, 32, 66, 96, 25, 62, 28, 92, 99],
       [18, 11, 39, 31, 93, 29, 23,  5, 11],
       [47, 23, 59, 63, 83, 31, 49, 11, 13],
       [13, 71, 18, 76, 88, 71,  2,  7, 28],
       [ 6, 39, 17, 38, 49, 63, 92, 97, 14],
       [44, 84, 46, 36, 48, 88, 31, 96,  4],
       [55, 46, 10, 34, 89, 25, 62, 39, 61],
       [27, 99, 40, 16, 19, 81, 51, 47, 50],
       [24, 16, 51, 46, 96, 79, 34, 62, 29]])

k = 23

In [25]:
array.reshape(-1)

array([29, 32, 66, 96, 25, 62, 28, 92, 99, 18, 11, 39, 31, 93, 29, 23,  5,
       11, 47, 23, 59, 63, 83, 31, 49, 11, 13, 13, 71, 18, 76, 88, 71,  2,
        7, 28,  6, 39, 17, 38, 49, 63, 92, 97, 14, 44, 84, 46, 36, 48, 88,
       31, 96,  4, 55, 46, 10, 34, 89, 25, 62, 39, 61, 27, 99, 40, 16, 19,
       81, 51, 47, 50, 24, 16, 51, 46, 96, 79, 34, 62, 29])

### Exercice 3 - Pas de négativité par ici ! (**)

Remplacer les valeurs négatives d'un array par la valeur 10.

_Bonus : Essayer de le faire sans boucle._

In [44]:
test_x = np.array([-1, -4, 0, 2, 3, 4, 5, -6])

In [47]:
mask = test_x < 0
test_x[mask] = 10
test_x

array([10, 10,  0,  2,  3,  4,  5, 10])

### Exercice 4 – Valeur moyenne des produits en stock (**, @)

On veut calculer la valeur moyenne d'un objet pris dans un entrepôt.

C'est-à-dire : l'entreprise stocke 20 types d'objets dans son entrepôt. Le prix individuel et la quantité de chaque objet sont disponibles ci-dessous. On veut savoir quelle est la valeur moyenne d'un objet pris au hasard.

_Indice : Il s'agit d'une moyenne de la valeur des objets pondérée par le nombre d'objets disponibles. Il existe une methode numpy spécialisée pour cette opération._

In [52]:
prices = {'EACCEB': 16.20509873265647,
         'DFDABF': 17.804842271631575,
         'BDAAAE': 6.034132127038211,
         'EBEDCC': 8.765726919661395,
         'BBEBFC': 9.670745692995943,
         'ADFBDD': 13.272839706755306,
         'CFEBDC': 7.073517242369817,
         'EADEAF': 12.639397686562715,
         'DCCDEF': 16.769485429582115,
         'DBDCDC': 14.474392462599267,
         'AFBAAF': 10.18958404384257,
         'DADBDD': 11.902219677537177,
         'CDFBBE': 14.219659680677468,
         'CACEBE': 7.43713434666425,
         'AFDDBC': 7.378245381252228,
         'CBDEFE': 10.883005811699599,
         'ECBBEB': 13.346825501979566,
         'ACAFDD': 6.185376071510866,
         'ACEACA': 7.922259506020709,
         'EBADBB': 12.538053632878556}

quantity = {'EACCEB': 4,
                 'DFDABF': 68,
                 'BDAAAE': 15,
                 'EBEDCC': 24,
                 'BBEBFC': 17,
                 'ADFBDD': 6,
                 'CFEBDC': 23,
                 'EADEAF': 54,
                 'DCCDEF': 90,
                 'DBDCDC': 83,
                 'AFBAAF': 3,
                 'DADBDD': 39,
                 'CDFBBE': 54,
                 'CACEBE': 35,
                 'AFDDBC': 44,
                 'CBDEFE': 34,
                 'ECBBEB': 69,
                 'ACAFDD': 42,
                 'ACEACA': 86,
                 'EBADBB': 81}

In [65]:
price = prices.values()
list(price)
qty = quantity.values()
list(qty)

np.average(list(price), weights = list(qty))

price = np.array(list(price))
qty = np.array(list(qty))

sum(price * qty) / sum(qty)

12.022411598561066

## Pandas

### Exercice 1 – Au coeur des marchés financiers (**)

Créer un DataFrame contenant la valeur de l'index du CAC40 sur le dernier mois.

Ensuite, afficher 10 lignes prises au hasard et compter le nombre de colonnes dans le DataFrame.

_Indice : [Yahoo Finance](https://finance.yahoo.com/quote/%5EFCHI/history/?guccounter=1&guce_referrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8&guce_referrer_sig=AQAAAKMlF49BUCnyOd_XKPns3bykhS6nmVu9Sn4Zn4DfuQAu6MYKL1JwEgjaMyUm8JvpwjxuDyy4ItGvnyw5bMr9YVwlOACJEAT2J0G28B8O5uhft6fSMADvYzNv5huL3aluRW5qngzh57FST4hbiGNod8ewfnfR9Dx1RZq7TfHlvpTK) est un bon site pour obtenir des données financières. Il existe ensuite plusieurs manières de charger les données Yahoo Finance dans ce notebook._

In [104]:
opening = pd.read_csv('/Users/thibaultdanel/Downloads/^FCHI.csv')
opening

Date         Open         High          Low        Close  \
0    2021-05-17  6397.220215  6410.209961  6349.330078  6367.350098   
1    2021-05-18  6406.180176  6412.910156  6343.549805  6353.669922   
2    2021-05-19  6292.049805  6310.490234  6192.330078  6262.549805   
3    2021-05-20  6296.250000  6343.580078  6267.549805  6343.580078   
4    2021-05-21  6360.879883  6402.100098  6351.950195  6386.410156   
..          ...          ...          ...          ...          ...   
255  2022-05-11  6173.100098  6269.729980  6137.240234  6269.729980   
256  2022-05-12  6130.689941  6238.250000  6098.220215  6206.259766   
257  2022-05-13  6250.160156  6363.240234  6238.790039  6362.680176   
258  2022-05-16  6315.680176  6369.049805  6286.020020  6347.770020   
259  2022-05-17  6379.339844  6448.330078  6373.729980  6434.359863   

       Adj Close     Volume  
0    6367.350098   62538700  
1    6353.669922   74129300  
2    6262.549805   92757600  
3    6343.580078   68528400  
4    6386.410156   75862000  
..           ...        ...  
255  6269.729980  106223700  
256  6206.259766  105839000  
257  6362.680176   85955800  
258  6347.770020   75092100  
259  6434.359863          0  

[260 rows x 7 columns]

### Exercice 2 – Comprendre un DataFrame (*)

Sur la DatafFrame `users` (voir plus bas) :
* Quel est le nombre d'observations dans le dataset ?
* Quel est le nombre de colonnes dans le dataset ?
* Afficher le nom de toutes les colonnes

BONUS :

* Renommer la colonne `postal_code`, `zip_code`
* Quel est le type de données de chaque colonne ?
* Combien d'`occupation` différentes y a-t-il dans ce dataset ?
* Quel est l'`occupation` la plus fréquente ?
* Quels sont les âges les moins fréquents ?

In [1]:
import pandas as pd
users = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user', 
                      sep='|', index_col='user_id')
users.head()

age gender  occupation zip_code
user_id                                 
1         24      M  technician    85711
2         53      F       other    94043
3         23      M      writer    32067
4         24      M  technician    43537
5         33      F       other    15213