# Analyse de données numériques - Solutions

Pour tous les exercices, le niveau de difficulté est indiqué par le code suivant :
* \* niveau facile
* \** niveau intermédiaire
* \*** niveau difficile

* **@** indique les exercices pour lesquels vous aurez besoin de chercher sur internet pour trouver des pistes de solution ou des exemples de code.

_Note : Pour faciliter la navigation dans les exercices, n'hésitez pas à activer l'extension "Table of Contents", après avoir installé les extensions de notebook `jupyter_contrib_nbextensions` (voir PDF sur la plateforme)._

## Numpy

D'abord, importer Numpy !

In [ ]:
import numpy as np

### Exercice 1 – Créer une matrice numpy (*)
Créer une matrice 4x4 avec des valeurs allant de 2 à 17.

In [ ]:
list(range(2, 18))

In [ ]:
np.arange(2, 18)

In [ ]:
# Méthode 1
np.arange(2, 18).reshape(4, 4)

In [ ]:
# Méthode 2
np.arange(16).reshape(4, 4) + 2

In [ ]:
# Méthode 3
np.random.randint(2, 18, size=(4, 4))

In [ ]:
# Méthode bonus
np.array(np.matrix('1 2 3; 4 5 6'))

### Exercice 2 - Sélectionner un élément dans un array (*, @)

Trouver le 23ème élément de l'array numpy ci-dessous. 

_Indice : L'une des solutions utilise une méthode numpy specifique que vous pourrez trouver sur internet. Une autre solution utilise `//` et `%`._

In [ ]:
array = np.array([[29, 32, 66, 96, 25, 62, 28, 92, 99],
       [18, 11, 39, 31, 93, 29, 23,  5, 11],
       [47, 23, 59, 63, 83, 31, 49, 11, 13],
       [13, 71, 18, 76, 88, 71,  2,  7, 28],
       [ 6, 39, 17, 38, 49, 63, 92, 97, 14],
       [44, 84, 46, 36, 48, 88, 31, 96,  4],
       [55, 46, 10, 34, 89, 25, 62, 39, 61],
       [27, 99, 40, 16, 19, 81, 51, 47, 50],
       [24, 16, 51, 46, 96, 79, 34, 62, 29]])

k = 23
array

In [ ]:
np.array(array.flat)[k-1]

In [ ]:
array.reshape(-1)[k-1]

In [ ]:
array.ravel()[k-1]

In [ ]:
array[ k // 9, k % 9 - 1 ]

In [ ]:
array[k // 9][k % 9 - 1]

### Exercice 3 - Pas de négativité par ici ! (**)

Remplacer les valeurs négatives d'un array par la valeur 10.

_Bonus : Essayer de le faire sans boucle._

In [2]:
import numpy as np

In [3]:
test_x = np.array([-1, -4, 0, 2, 3, 4, 5, -6])
test_x

array([-1, -4,  0,  2,  3,  4,  5, -6])

In [4]:
list(range(len(test_x)))

[0, 1, 2, 3, 4, 5, 6, 7]

In [5]:
for i in range(len(test_x)):
    if test_x[i] < 0:
        test_x[i] = 10

test_x

array([10, 10,  0,  2,  3,  4,  5, 10])

In [6]:
for i, x in enumerate(test_x):
    if x < 0:
        test_x[i] = 10
        
test_x

array([10, 10,  0,  2,  3,  4,  5, 10])

Méthode sans boucle:

In [7]:
test_x[ test_x < 0 ] = 10

In [8]:
test_x[ test_x < 0 ] = 10
test_x

array([10, 10,  0,  2,  3,  4,  5, 10])

### Exercice 4 – Valeur moyenne des produits en stock (**, @)

On veut calculer la valeur moyenne d'un objet pris dans un entrepôt.

C'est-à-dire : l'entreprise stocke 20 types d'objets dans son entrepôt. Le prix individuel et la quantité de chaque objet sont disponibles ci-dessous. On veut savoir quelle est la valeur moyenne d'un objet pris au hasard.

_Indice : Il s'agit d'une moyenne de la valeur des objets pondérée par le nombre d'objets disponibles. Il existe une methode numpy spécialisée pour cette opération._

In [10]:
prices = {'EACCEB': 16.20509873265647,
         'DFDABF': 17.804842271631575,
         'BDAAAE': 6.034132127038211,
         'EBEDCC': 8.765726919661395,
         'BBEBFC': 9.670745692995943,
         'ADFBDD': 13.272839706755306,
         'CFEBDC': 7.073517242369817,
         'EADEAF': 12.639397686562715,
         'DCCDEF': 16.769485429582115,
         'DBDCDC': 14.474392462599267,
         'AFBAAF': 10.18958404384257,
         'DADBDD': 11.902219677537177,
         'CDFBBE': 14.219659680677468,
         'CACEBE': 7.43713434666425,
         'AFDDBC': 7.378245381252228,
         'CBDEFE': 10.883005811699599,
         'ECBBEB': 13.346825501979566,
         'ACAFDD': 6.185376071510866,
         'ACEACA': 7.922259506020709,
         'EBADBB': 12.538053632878556}

quantity = {'EACCEB': 4,
             'DFDABF': 68,
             'BDAAAE': 15,
             'EBEDCC': 24,
             'BBEBFC': 17,
             'ADFBDD': 6,
             'CFEBDC': 23,
             'EADEAF': 54,
             'DCCDEF': 90,
             'DBDCDC': 83,
             'AFBAAF': 3,
             'DADBDD': 39,
             'CDFBBE': 54,
             'CACEBE': 35,
             'AFDDBC': 44,
             'CBDEFE': 34,
             'ECBBEB': 69,
             'ACAFDD': 42,
             'ACEACA': 86,
             'EBADBB': 81}

Méthode longue :

In [11]:
list(prices.values())

[16.20509873265647,
 17.804842271631575,
 6.034132127038211,
 8.765726919661395,
 9.670745692995943,
 13.272839706755306,
 7.073517242369817,
 12.639397686562715,
 16.769485429582115,
 14.474392462599267,
 10.18958404384257,
 11.902219677537177,
 14.219659680677468,
 7.43713434666425,
 7.378245381252228,
 10.883005811699599,
 13.346825501979566,
 6.185376071510866,
 7.922259506020709,
 12.538053632878556]

In [23]:
list(quantity.values())

[4, 68, 15, 24, 17, 6, 23, 54, 90, 83, 3, 39, 54, 35, 44, 34, 69, 42, 86, 81]

In [16]:
p = np.array(list(prices.values()))
q = np.array(list(quantity.values()))

In [17]:
sum(p * q) / q.sum()

12.022411598561066

In [21]:
# Valeur moyenne pour 1 produit
np.average(list(prices.values()), weights=list(quantity.values()))

12.022411598561066

In [19]:
# Valeur moyenne pour 1 catégorie
np.mean(q * p)

523.5760251173344

## Pandas

### Exercice 1 – Au coeur des marchés financiers (**)

Créer un DataFrame contenant la valeur de l'index du CAC40 sur le dernier mois.

Ensuite, afficher 10 lignes prises au hasard et compter le nombre de colonnes dans le DataFrame.

_Indice : [Yahoo Finance](https://finance.yahoo.com/quote/%5EFCHI/history/?guccounter=1&guce_referrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8&guce_referrer_sig=AQAAAKMlF49BUCnyOd_XKPns3bykhS6nmVu9Sn4Zn4DfuQAu6MYKL1JwEgjaMyUm8JvpwjxuDyy4ItGvnyw5bMr9YVwlOACJEAT2J0G28B8O5uhft6fSMADvYzNv5huL3aluRW5qngzh57FST4hbiGNod8ewfnfR9Dx1RZq7TfHlvpTK) est un bon site pour obtenir des données financières. Il existe ensuite plusieurs manières de charger les données Yahoo Finance dans ce notebook._

In [30]:
import pandas as pd

In [29]:
cac40 = pd.read_csv("/Users/thibaultdanel/Downloads/^FCHI.csv")
cac40.head()

Date         Open         High          Low        Close  \
0  2021-05-17  6397.220215  6410.209961  6349.330078  6367.350098   
1  2021-05-18  6406.180176  6412.910156  6343.549805  6353.669922   
2  2021-05-19  6292.049805  6310.490234  6192.330078  6262.549805   
3  2021-05-20  6296.250000  6343.580078  6267.549805  6343.580078   
4  2021-05-21  6360.879883  6402.100098  6351.950195  6386.410156   

     Adj Close    Volume  
0  6367.350098  62538700  
1  6353.669922  74129300  
2  6262.549805  92757600  
3  6343.580078  68528400  
4  6386.410156  75862000

In [28]:
cac40 = pd.read_clipboard()
cac40.head(10)

Empty DataFrame
Columns: [/Users/thibaultdanel/Downloads/^FCHI.csv]
Index: []

In [ ]:
cac40.sample(10)

In [ ]:
cac40.columns

In [ ]:
len(cac40.columns)

### Exercice 2 – Comprendre un DataFrame (*)

Sur la DatafFrame `users` (voir plus bas) :
* Quel est le nombre d'observations dans le dataset ?
* Quel est le nombre de colonnes dans le dataset ?
* Afficher le nom de toutes les colonnes

BONUS :

* Renommer la colonne `postal_code`, `zip_code`
* Quel est le type de données de chaque colonne ?
* Combien d'`occupation` différentes y a-t-il dans ce dataset ?
* Quel est l'`occupation` la plus fréquente ?
* Quels sont les âges les moins fréquents ?

In [ ]:
users = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user', 
                      sep='|', index_col='user_id')
users.head()

In [ ]:
len(users) # nombre d'observations

In [ ]:
users.shape[0] # nombre d'observations

In [ ]:
users.shape[1]  # nombre de colonnes

In [ ]:
users.columns  # noms des colonnes

In [ ]:
# Renommer les colonnes
users.columns = ['age', 'gender', 'occupation', 'postal_code']
users

In [ ]:
# Renommer une colonne
users = users.rename(columns={'postal_code':'zip_code', 'occupation':'metier'})
users

In [ ]:
users.info()  # types des colonnes

In [ ]:
users.dtypes  # types des colonnes

In [ ]:
len(users['metier'].unique()) # nb of different occupations

In [ ]:
users['metier'].value_counts() # occupation la plus fréquente 

In [ ]:
users['metier'].mode() # occupation la plus fréquente 

In [ ]:
users['age'].value_counts().tail(10)  # age le moins fréquent