# Numpy

On doit d'abord importer le package ! 

In [170]:
import numpy as np

In [171]:
np.__version__

'1.20.3'

### Propriétés des arrays numpy

On crée généralement un array en transformant une liste :

In [ ]:
my_array = np.array([1, 2, 3])
my_array

In [ ]:
type(list(my_array)) # transformation d'array en liste

Contrairement aux listes (qui ont une longeur), les arrays ont une **shape**. En effet, les arrays permettent de réprésenter des données sur **une dimension** (= liste, vecteur) mais aussi sous forme de **matrices (2D)** ou de **tenseurs (3D et plus)**.

In [ ]:
my_array.shape

Cette écriture équivaut à `(3,1)` (1 ligne, 3 colonnes).

In [193]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

In [190]:
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

Quelle va être la `shape` de cet array ?

In [180]:
array_2d.shape

(2, 3)

In [194]:
mask = array_2d < 4
array_2d[mask] *= 250
array_2d

array([[250, 500, 750],
       [  4,   5,   6]])

Cela siginifie que notre  `array_2d` est une matrice de 2 lignes et 3 colonnes

L'indexing et le slicing des arrays s'effectue de la même manière que pour les listes (`[ ]`), avec la possibilité de sélectionner des données dans plusieurs dimensions :

In [ ]:
array_2d

Pouvez-vous deviner le contenu des prochaines cellules ?

In [175]:
array_2d[0] # Encore et toujours les crochets de slicing ('square brackets')

array([1, 2, 3])

In [176]:
array_2d[0][0]

1

In [177]:
array_2d[1, :2]

array([4, 5])

Enfin, l'une des différences majeures entre les arrays et les listes est que les arrays ne peuvent contenir qu'un seul type de valeur à la fois - on ne peut pas mixer les types comme dans les listes.

In [174]:
my_list = [1, 2.5, True, 'DataBird']

In [173]:
my_array = np.array(my_list)
my_array

array(['1', '2.5', 'True', 'DataBird'], dtype='<U32')

Que s'est-il passé ? La cellule n'a pas généré d'erreur, en revanche tous les éléments ont été convertis vers le type le plus généraliste : `str`.

In [172]:
np.array([1, 2, 3.5]) # ici, les integers sont convertis en floats

array([1. , 2. , 3.5])

L'avantage : éviter les erreurs lors des calculs sur des colonnes. Cette propriété nous assure que si l'on veut par exemple multiplier 2 colonnes, ou calculer la moyenne d'une colonne, elle ne contiendra que des float (par ex), ce qui évitera une `TypeError` !

Voyons maintenant les opérations possibles avec des arrays numpy.