# Numpy

In [14]:
import numpy as np

### Opérations sur les arrays numpy

Les opérations autorisées sur les arrays sont plus nombreuses que sur les listes - c'est un avantage de numpy.

In [15]:
2 * [10, 20, 30] / 10

TypeError: unsupported operand type(s) for /: 'list' and 'int'

Avec une liste on aurait besoin d'une boucle ! Mais pas avec numpy :

In [17]:
2 * np.array([10, 20, 30]) / 10

array([2., 4., 6.])

En plus de ces opérations simples, de nombreuses méthodes existent pour créer et transformer des arrays :

In [18]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
eight_digits = np.arange(9) # similaire à range(9) pour les listes
eight_digits

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
eight_digits.shape

(9,)

In [21]:
eight_digits.reshape((3, 3)) # on indique la shape souhaitée en argument

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Enfin, les calculs sur des array sont généralement plus rapides que sur des listes.

Comparons les 2 méthodes sur une opération simple, diviser une série d'1 million d'éléments. Est-il mieux de le faire avec une  `list` ou un  `array` ?

In [22]:
%%time

numbers_list = list(range(1000000))

for i in range(len(numbers_list)):
    numbers_list[i] = numbers_list[i] / 2

CPU times: user 144 ms, sys: 58.8 ms, total: 202 ms
Wall time: 470 ms


In [23]:
%%time

numbers_array = np.arange(1000000)

doubled_array = 2 * numbers_array

CPU times: user 4.23 ms, sys: 7.73 ms, total: 12 ms
Wall time: 9.62 ms


Essayez de deviner l'output de la prochaine cellule :

In [25]:
doubled_array[:5]

array([0, 2, 4, 6, 8])

Les arrays sont nettement plus rapides - et plus la taille des données augmentera, plus l'utilisation de Numpy deviendra pertinente (en plus d'être plus lisible). 

C'est la raison pour laquelle les tableaux pandas, que nous allons étudier juste après, sont fondés sur des arrays numpy ! Rendez-vous dans la suite du module pour commencer à analyser des données sous forme de tableaux avec Pandas.

In [35]:
import numpy as np

ar = np.arange(10)
ar.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [51]:
import numpy as np
arr = [12,15,18,19,20]
arr_w = [0.1,0.1,0.1,0.2,0.5]

print("Weighted Average Function: ",np.average(arr,weights = arr_w))

Weighted Average Function:  18.3
